DROP DATABASE IF EXISTS DVDLibrary;
CREATE DATABASE DVDLibrary;

USE DVDLibrary;

CREATE TABLE Director(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL
);

CREATE TABLE DVD(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    directorID INT NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    releaseDate DATE NOT NULL,
    rating VARCHAR(5) NOT NULL,
    FOREIGN KEY (directorID) REFERENCES Director(ID)
);